# Generated by Django 4.1.5 on 2023-01-12 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("d6d0a8ba-7080-47a7-ae34-150045c12df0"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("mobile", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("829c5f04-6e11-4e31-96bf-92de8757f9a5"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile_image"),
                ),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("news_update", models.BooleanField(default=False)),
                ("tips_and_tutorial", models.BooleanField(default=False)),
                ("user_search", models.BooleanField(default=False)),
                (
                    "reminders",
                    models.CharField(
                        choices=[
                            ("ALL_REMINDERS", "ALL_REMINDERS"),
                            ("IMPORTANT_REMINDERS", "IMPORTANT_REMINDERS"),
                            ("NO_REMINDERS", "NO_REMINDERS"),
                        ],
                        default="ALL_REMINDERS",
                        max_length=250,
                    ),
                ),
                (
                    "mentions",
                    models.CharField(
                        choices=[
                            ("ALL_MENTIONS", "ALL_MENTIONS"),
                            ("IMPORTANT_MENTIONS", "IMPORTANT_MENTIONS"),
                            ("NO_MENTIONS", "NO_MENTIONS"),
                        ],
                        default="ALL_MENTIONS",
                        max_length=250,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
