# Generated by Django 4.1.5 on 2023-01-12 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b43c61f2-2120-4e21-8bd1-c31201b3f258"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0df976a1-58ec-4d7c-86f7-aed5dc58bae9"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
