# Generated by Django 4.1.5 on 2023-01-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=True),
        ),
    ]
