# Generated by Django 4.1.5 on 2023-01-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_user_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
