# Generated by Django 4.1.5 on 2023-01-12 10:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EstateUtility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("1c98615b-9638-44f3-ad04-b8d7c72304e1"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "DAILY"),
                            ("WEEKLY", "WEEKLY"),
                            ("MONTHLY", "MONTHLY"),
                            ("YEARLY", "YEARLY"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "MANDATORY"),
                            ("NOT_MANDATORY", "NOT_MANDATORY"),
                        ],
                        max_length=50,
                    ),
                ),
                ("due_date", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="EstateUtilitySubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("c690f212-e5fb-4dd8-9cfb-efaed8cd7aa3"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("FLUTTERWAVE", "FLUTTERWAVE"),
                            ("PAYSTACK", "PAYSTACK"),
                            ("BANK", "BANK"),
                        ],
                        max_length=250,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        max_length=50,
                        verbose_name=(
                            ("PENDING", "PENDING"),
                            ("FAILED", "FAILED"),
                            ("SUCCESS", "SUCCESS"),
                        ),
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("paid_date", models.DateField()),
                ("due_date", models.DateField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
