# Generated by Django 4.1.5 on 2023-01-12 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0001_initial"),
        ("estate_users", "0001_initial"),
        ("estate_utilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estateutilitysubscription",
            name="estate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
            ),
        ),
        migrations.AddField(
            model_name="estateutilitysubscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="estate_users.estateuser",
            ),
        ),
        migrations.AddField(
            model_name="estateutility",
            name="estate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
            ),
        ),
        migrations.AddField(
            model_name="estateutility",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estate_users.estateuser",
            ),
        ),
    ]
