# Generated by Django 4.1.5 on 2023-01-13 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_utilities", "0009_alter_estateutility_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estateutility",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="estateutilitysubscription",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterField(
            model_name="estateutility",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f9182c15-8458-430f-b189-83db8570eb9f"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="estateutilitysubscription",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a1f01242-3aa6-4790-a32a-5fd76b7aef44"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
