# Generated by Django 4.1.5 on 2023-01-15 10:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_users",
            "0007_alter_estateuser_options_estateuser_created_by_and_more",
        ),
        ("estates", "0011_estatezone"),
        ("estate_utilities", "0013_alter_estateutility_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estateutilitysubscription",
            name="transaction_id",
        ),
        migrations.AlterField(
            model_name="estateutility",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a4f5143f-25ca-4be9-a315-f3af2257d0c9"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="estateutilitysubscription",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8cf89500-b43c-4ae2-913a-375be368b2ac"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="UtilityTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.FloatField(default=0)),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLUTTERWAVE", "FLUTTERWAVE"),
                            ("PAYSTACK", "PAYSTACK"),
                            ("BANK", "BANK"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "PENDING"),
                            ("FAILED", "FAILED"),
                            ("SUCCESS", "SUCCESS"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=100, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
                    ),
                ),
                (
                    "estate_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estate_users.estateuser",
                    ),
                ),
                (
                    "estate_utility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estate_utilities.estateutility",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AddField(
            model_name="estateutilitysubscription",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estate_utilities.utilitytransaction",
            ),
        ),
    ]
