# Generated by Django 4.1.5 on 2023-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_utilities", "0030_alter_estateutility_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="estateutility",
            name="collection_target",
            field=models.CharField(
                blank=True,
                choices=[("RESIDENT", "RESIDENT"), ("EXTERNAL", "EXTERNAL")],
                max_length=50,
                null=True,
            ),
        ),
    ]
