# Generated by Django 4.1.5 on 2023-01-12 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d7378fa3-9727-443c-a701-7e5d8a7c4fbd"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
