# Generated by Django 4.1.5 on 2023-01-12 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0003_alter_estate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e1dd5043-06d5-4179-b0d8-09f3ba2d9906"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
