# Generated by Django 4.1.5 on 2023-01-12 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0004_alter_estate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4bf8fa5d-ce30-408a-abcd-474c489db784"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
