# Generated by Django 4.1.5 on 2023-01-12 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0006_alter_estate_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
