# Generated by Django 4.1.5 on 2023-01-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0007_alter_estate_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="estate",
            name="estate_subscription",
        ),
        migrations.AlterField(
            model_name="estatesubscription",
            name="estate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
            ),
        ),
    ]
