# Generated by Django 4.1.5 on 2023-01-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0011_estatezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="state",
            field=models.CharField(default="INACTIVE", max_length=250),
        ),
    ]
