# Generated by Django 4.1.5 on 2023-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0012_alter_estate_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="estate",
            name="status",
            field=models.CharField(default="INACTIVE", max_length=250),
        ),
        migrations.AlterField(
            model_name="estate",
            name="state",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
