# Generated by Django 4.1.5 on 2023-01-23 14:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0013_estate_status_alter_estate_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estate",
            name="status",
            field=models.CharField(default="ACTIVE", max_length=250),
        ),
        migrations.CreateModel(
            name="EstateStreet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
                    ),
                ),
                (
                    "estate_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estates.estatezone",
                    ),
                ),
            ],
        ),
    ]
