# Generated by Django 4.1.5 on 2023-07-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0014_alter_estate_status_estatestreet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatestreet',
            name='estate_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estates.estatezone'),
        ),
    ]
