# Generated by Django 4.1.5 on 2023-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0015_alter_estatestreet_estate_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='status',
            field=models.CharField(default='PENDING', max_length=250),
        ),
    ]
