# Generated by Django 4.1.5 on 2023-08-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0016_alter_estate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
    ]
