# Generated by Django 4.1.5 on 2023-01-26 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estates", "0014_alter_estate_status_estatestreet"),
        ("estate_users", "0012_alter_estateuser_user_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstateComplaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("reason", models.CharField(max_length=500)),
                (
                    "receivers",
                    models.CharField(
                        choices=[
                            ("ADMIN", "ADMIN"),
                            ("RESIDENT", "RESIDENT"),
                            ("EXTERNAL", "EXTERNAL"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("RESOLVED", "RESOLVED"), ("PENDING", "PENDING")],
                        max_length=50,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "estate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
                    ),
                ),
                (
                    "estate_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="estate_user",
                        to="estate_users.estateuser",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_by",
                        to="estate_users.estateuser",
                    ),
                ),
            ],
        ),
    ]
