# Generated by Django 4.1.5 on 2023-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_complaints", "0002_alter_estatecomplaint_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estatecomplaint",
            name="receivers",
            field=models.CharField(
                choices=[
                    ("SECURITY", "SECURITY"),
                    ("HEAD_OF_SECURITY", "HEAD_OF_SECURITY"),
                    ("FINANCIAL_SECURITY", "FINANCIAL_SECURITY"),
                    ("PRESIDENT", "PRESIDENT"),
                    ("VICE_PRESIDENT", "VICE_PRESIDENT"),
                ],
                max_length=50,
            ),
        ),
    ]
