# Generated by Django 4.1.5 on 2023-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_complaints", "0003_alter_estatecomplaint_receivers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estatecomplaint",
            options={"ordering": ["-timestamp"]},
        ),
    ]
