# Generated by Django 4.1.5 on 2023-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_complaints', '0004_alter_estatecomplaint_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatecomplaint',
            name='receivers',
            field=models.CharField(choices=[('CHIEF_SECRETARY_OFFICER', 'CHIEF_SECRETARY_OFFICER'), ('FINANCIAL_SECRETARY', 'FINANCIAL_SECRETARY'), ('ESTATE_MANAGER', 'ESTATE_MANAGER'), ('EXCOS', 'EXCOS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='estatecomplaint',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
