# Generated by Django 4.1.5 on 2023-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_complaints', '0005_alter_estatecomplaint_receivers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatecomplaint',
            name='case_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
