# Generated by Django 4.1.5 on 2023-08-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_complaints', '0006_estatecomplaint_case_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatecomplaint',
            name='receivers',
            field=models.CharField(choices=[('CHIEF_SECURITY_OFFICER', 'CHIEF_SECURITY_OFFICER'), ('FINANCIAL_SECRETARY', 'FINANCIAL_SECRETARY'), ('ESTATE_MANAGER', 'ESTATE_MANAGER'), ('EXCOS', 'EXCOS')], max_length=50),
        ),
    ]
