# Generated by Django 4.1.5 on 2023-01-12 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_users", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("19677466-42a5-484b-a701-9c41818f5d54"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
