# Generated by Django 4.1.5 on 2023-01-12 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_users", "0004_alter_estateuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d04e51ca-d440-4806-bbdf-b5c504064332"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
