# Generated by Django 4.1.5 on 2023-01-12 11:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_users", "0005_alter_estateuser_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateuser",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
