# Generated by Django 4.1.5 on 2023-01-13 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("estate_users", "0006_alter_estateuser_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estateuser",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AddField(
            model_name="estateuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="estateuser",
            name="invited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="estateuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EstateUserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile_image"),
                ),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("news_update", models.BooleanField(default=False)),
                ("tips_and_tutorial", models.BooleanField(default=False)),
                ("user_search", models.BooleanField(default=False)),
                (
                    "reminders",
                    models.CharField(
                        choices=[
                            ("ALL_REMINDERS", "ALL_REMINDERS"),
                            ("IMPORTANT_REMINDERS", "IMPORTANT_REMINDERS"),
                            ("NO_REMINDERS", "NO_REMINDERS"),
                        ],
                        default="ALL_REMINDERS",
                        max_length=250,
                    ),
                ),
                (
                    "mentions",
                    models.CharField(
                        choices=[
                            ("ALL_MENTIONS", "ALL_MENTIONS"),
                            ("IMPORTANT_MENTIONS", "IMPORTANT_MENTIONS"),
                            ("NO_MENTIONS", "NO_MENTIONS"),
                        ],
                        default="ALL_MENTIONS",
                        max_length=250,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "estate_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estate_user_profile",
                        to="estate_users.estateuser",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
