# Generated by Django 4.1.5 on 2023-01-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_users",
            "0007_alter_estateuser_options_estateuser_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateuser",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_user",
                to="estate_users.estateuser",
            ),
        ),
    ]
