# Generated by Django 4.1.5 on 2023-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_users", "0008_alter_estateuser_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "ADMIN"),
                    ("RESIDENT", "RESIDENT"),
                    ("EXTERNAL", "EXTERNAL"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
