# Generated by Django 4.1.5 on 2023-01-23 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0014_alter_estate_status_estatestreet"),
        ("estate_users", "0010_alter_estateuser_user_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="estateuser",
            name="estate_street",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estates.estatestreet",
            ),
        ),
        migrations.AddField(
            model_name="estateuser",
            name="estate_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estates.estatezone",
            ),
        ),
    ]
