# Generated by Django 4.1.5 on 2023-07-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_users', '0013_estateuser_emergency_service_estateuser_gate_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateuser',
            name='role',
            field=models.CharField(blank=True, choices=[('FACILITY_MANAGER', 'FACILITY_MANAGER'), ('PROPERTY_MANAGER', 'PROPERTY_MANAGER'), ('RESIDENT', 'RESIDENT'), ('COMMUNITY_ASSOCIATION_EXCO', 'COMMUNITY_ASSOCIATION_EXCO'), ('PROPERTY_DEVELOPER', 'PROPERTY_DEVELOPER'), ('PROPERTY_DEVELOPER', 'PROPERTY_DEVELOPER'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=250, null=True),
        ),
    ]
