# Generated by Django 4.1.5 on 2023-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_users', '0014_estateuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateuserprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
