# Generated by Django 4.1.5 on 2023-07-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_users', '0015_alter_estateuserprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateuser',
            name='estate_user_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
