# Generated by Django 4.1.5 on 2023-08-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_users', '0019_alter_estateuser_user_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateuser',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING')], default='PENDING', max_length=250),
        ),
    ]
