# Generated by Django 4.1.5 on 2023-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_users', '0021_alter_estateuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateuser',
            name='designation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='estateuser',
            name='relationship',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
