# Generated by Django 4.1.5 on 2023-09-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_users', '0022_estateuser_designation_estateuser_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estateuser',
            name='designation',
            field=models.CharField(blank=True, choices=[('SECURITY', 'SECURITY'), ('HOUSE_KEEPER', 'HOUSE_KEEPER'), ('LESSON_TEACHER', 'LESSON_TEACHER'), ('DRIVER', 'DRIVER'), ('GARDENER', 'GARDENER'), ('NURSE', 'NURSE'), ('CHEF', 'CHEF'), ('OTHERS', 'OTHERS')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='estateuser',
            name='relationship',
            field=models.CharField(blank=True, choices=[('CHILD', 'CHILD'), ('SIBLING', 'SIBLING'), ('PARENT', 'PARENT'), ('RELATIVE', 'RELATIVE'), ('OTHERS', 'OTHERS')], max_length=250, null=True),
        ),
    ]
