# Generated by Django 4.1.5 on 2023-01-31 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("estate_users", "0012_alter_estateuser_user_category"),
        ("estates", "0014_alter_estate_status_estatestreet"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstateAccessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=250)),
                ("last_name", models.CharField(max_length=250)),
                ("phone", models.CharField(blank=True, max_length=250, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.CharField(blank=True, max_length=250, null=True)),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("access_code", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "estate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estates.estate",
                    ),
                ),
                (
                    "estate_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_log_created_by",
                        to="estate_users.estateuser",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_log_updated_by",
                        to="estate_users.estateuser",
                    ),
                ),
            ],
        ),
    ]
