# Generated by Django 4.1.5 on 2023-02-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_access_logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estateaccesslog",
            name="access",
            field=models.CharField(
                choices=[("GRANT", "GRANT"), ("REVOKE", "REVOKE")],
                default="GRANT",
                max_length=50,
            ),
        ),
    ]
