# Generated by Django 4.1.5 on 2023-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_access_logs", "0002_estateaccesslog_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estateaccesslog",
            options={"ordering": ["-timestamp"]},
        ),
    ]
