# Generated by Django 4.1.5 on 2023-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_access_logs', '0003_alter_estateaccesslog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateaccesslog',
            name='category',
            field=models.CharField(blank=True, choices=[('ONE_TIME_GUEST', 'ONE_TIME_GUEST'), ('REGULAR_GUEST', 'REGULAR_GUEST'), ('ARTISAN', 'ARTISAN'), ('TAXI', 'TAXI'), ('EVENT', 'EVENT')], default='ONE_TIME_GUEST', max_length=250, null=True),
        ),
    ]
