# Generated by Django 4.1.5 on 2023-07-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_access_logs', '0004_estateaccesslog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateaccesslog',
            name='access_type',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'ONE_TIME'), ('PERMANENT', 'PERMANENT')], default='ONETIME', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estateaccesslog',
            name='verified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='category',
            field=models.CharField(blank=True, choices=[('VISITOR', 'VISITOR'), ('ARTISAN', 'ARTISAN'), ('TAXI', 'TAXI'), ('DELIVERY', 'DELIVERY'), ('EVENT', 'EVENT'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=250, null=True),
        ),
    ]
