# Generated by Django 4.1.5 on 2023-09-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_access_logs', '0006_alter_estateaccesslog_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateaccesslog',
            name='access_log_type',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('BUSINESS', 'BUSINESS'), ('WAYBILL', 'WAYBILL')], default='PRIVATE', max_length=250),
        ),
        migrations.AddField(
            model_name='estateaccesslog',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='estateaccesslog',
            name='item_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='estateaccesslog',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='estateaccesslog',
            name='waybill_type',
            field=models.CharField(blank=True, choices=[('INBOUND_ITEM', 'INBOUND_ITEM'), ('OUTBOUND_ITEM', 'OUTBOUND_ITEM')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='access',
            field=models.CharField(blank=True, choices=[('GRANT', 'GRANT'), ('REVOKE', 'REVOKE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='category',
            field=models.CharField(blank=True, choices=[('VISITOR', 'VISITOR'), ('ARTISAN', 'ARTISAN'), ('TAXI', 'TAXI'), ('DELIVERY', 'DELIVERY'), ('EVENT', 'EVENT'), ('VEHICLE', 'VEHICLE'), ('CLIENT', 'CLIENT'), ('PEDESTRIAN', 'PEDESTRIAN'), ('HOUSEHOLD_ITEMS', 'HOUSEHOLD_ITEMS'), ('OTHERS', 'OTHERS')], default='OTHERS', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='estateaccesslog',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
