# Generated by Django 4.1.5 on 2023-02-05 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "estate_users",
            "0013_estateuser_emergency_service_estateuser_gate_pass_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAdminNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ESTATE_CREATED", "ESTATE_CREATED"),
                            ("MESSAGE", "MESSAGE"),
                        ],
                        max_length=50,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="EstateUserNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("MESSAGE", "MESSAGE"),
                            ("ADVERT", "ADVERT"),
                            ("REMINDER", "REMINDER"),
                            ("ALERT", "ALERT"),
                            ("ANNOUNCEMENT", "ANNOUNCEMENT"),
                        ],
                        max_length=50,
                    ),
                ),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "estate_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estate_users.estateuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
