# Generated by Django 4.1.5 on 2023-02-01 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_adverts", "0003_alter_estateannouncement_announcement_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estateannouncement",
            name="announcement_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 1, 14, 47, 45, 630676, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="estatereminder",
            name="reminder_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 2, 1, 14, 47, 52, 573448, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
