# Generated by Django 4.1.5 on 2023-08-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_adverts', '0004_alter_estateannouncement_announcement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estateadvertisement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
