# Generated by Django 4.1.5 on 2023-02-05 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_webhooks", "0002_rename_json_webhook_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhook",
            options={"ordering": ["-timestamp"]},
        ),
    ]
