# Generated by Django 4.1.5 on 2023-01-12 10:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("FREE", "FREE"),
                            ("ESSENTIAL", "ESSENTIAL"),
                            ("STANDARD", "STANDARD"),
                            ("PREMIUM", "PREMIUM"),
                        ],
                        max_length=250,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        max_length=250,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
