# Generated by Django 4.1.5 on 2023-01-12 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0009_delete_estatesubscription"),
        ("estate_plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstateSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                        max_length=250,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FLUTTERWAVE", "FLUTTERWAVE"),
                            ("PAYSTACK", "PAYSTACK"),
                            ("BANK", "BANK"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "estate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="estates.estate"
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="estate_plans.plan",
                    ),
                ),
            ],
        ),
    ]
