# Generated by Django 4.1.5 on 2023-01-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_plans", "0002_estatesubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estatesubscription",
            options={"ordering": ("-timestamp",)},
        ),
    ]
