# Generated by Django 4.1.5 on 2023-01-15 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estate_plans", "0004_alter_plan_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="estatetransaction",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.RemoveField(
            model_name="estatesubscription",
            name="transaction_ref",
        ),
        migrations.RemoveField(
            model_name="estatetransaction",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="estatetransaction",
            name="estate",
        ),
        migrations.AddField(
            model_name="estatetransaction",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estate_plans.plan",
            ),
        ),
        migrations.AlterField(
            model_name="estatetransaction",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                default="SUCCESS",
                max_length=250,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="estatetransaction",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="estatetransaction",
            name="transaction_reference",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "ACTIVE"), ("INACTIVE", "INACTIVE")],
                default="ACTIVE",
                max_length=250,
            ),
        ),
    ]
