# Generated by Django 4.1.5 on 2023-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estate_plans", "0005_alter_estatetransaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estatetransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("FAILED", "FAILED"),
                    ("SUCCESS", "SUCCESS"),
                ],
                default="PENDING",
                max_length=250,
            ),
        ),
    ]
