# Generated by Django 4.1.5 on 2023-01-15 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estates", "0011_estatezone"),
        (
            "estate_users",
            "0007_alter_estateuser_options_estateuser_created_by_and_more",
        ),
        ("estate_plans", "0006_alter_estatetransaction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="estatetransaction",
            name="estate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estates.estate",
            ),
        ),
        migrations.AddField(
            model_name="estatetransaction",
            name="estate_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="estate_users.estateuser",
            ),
        ),
    ]
