# Generated by Django 4.1.5 on 2023-01-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_plans", "0008_alter_estatetransaction_transaction_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estatesubscription",
            old_name="subscription",
            new_name="plan",
        ),
    ]
