# Generated by Django 4.1.5 on 2023-02-23 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("estate_group_chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessage",
            name="read",
        ),
    ]
