# Generated by Django 4.1.5 on 2023-01-12 10:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b147e859-8429-42cc-a415-294b3aeab749"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("927274da-0f63-4f97-a93b-66cc50bb656f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
