# Generated by Django 4.1.5 on 2023-01-12 10:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0003_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ba7b860a-8c66-4507-9cad-a5fffc4baec7"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4f87809d-a7ff-4ced-821a-e777ea06f49a"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
