# Generated by Django 4.1.5 on 2023-01-12 11:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0005_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("036a6f59-8093-4952-829e-cdc284c29e21"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("62a23459-2656-47d4-9eac-dd4a894e897c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
