# Generated by Django 4.1.5 on 2023-01-12 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0007_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("253ee8a9-1db1-4876-b222-e03c4bc96b6c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ef713c1f-d5d9-464f-b3de-27e77dc21c93"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
