# Generated by Django 4.1.5 on 2023-01-13 12:26

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0009_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AddField(
            model_name="conversation",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a6bc3802-7a80-4af9-bfb1-9f1c2ababac1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("44e983af-dddc-400d-806b-d56336165984"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
