# Generated by Django 4.1.5 on 2023-01-13 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0010_alter_conversation_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0c23f36e-d978-4bfd-a2c1-eb38a234805b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("97c9f565-f9d1-435f-af16-3a555ff1c359"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
