# Generated by Django 4.1.5 on 2023-01-15 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0012_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("bc91d785-eb90-4669-bc00-154a68b1da1f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8e5ecb13-a202-4d84-99ac-5357bda92d48"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
