# Generated by Django 4.1.5 on 2023-01-15 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0013_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4b893e3c-ae4f-42a3-bd05-f057e1519ad1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("acc79170-c094-4e48-805c-cbd9db317f08"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
