# Generated by Django 4.1.5 on 2023-01-15 10:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0014_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0d26a8db-0240-41ed-9cca-a2af84caaf56"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("31b7fdd5-270e-44bf-8871-081e58a0bc48"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
