# Generated by Django 4.1.5 on 2023-01-15 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0018_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("da8cdd9c-5a0d-4ce9-9c30-7fe15465ae62"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("1f3fc522-868f-489e-b0ff-5e4bedc08646"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
