# Generated by Django 4.1.5 on 2023-01-15 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0019_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d899e699-3e71-4dc0-9899-84ce2bec264e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c89dcbed-4b54-450b-bddb-0ea372407ef5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
