# Generated by Django 4.1.5 on 2023-01-15 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0021_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c41dec46-15cd-4170-a436-108f8a94d92b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7efc9bcb-b3f0-49ea-97a9-73555d5cb533"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
