# Generated by Django 4.1.5 on 2023-01-15 16:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0022_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b9f22dcf-6ce1-40aa-adfc-92e4dbdebd7d"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("60d76f95-551b-4079-a755-9f5414745c5e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
