# Generated by Django 4.1.5 on 2023-01-15 19:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0023_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("8fc543b5-1f07-44c2-84bf-fcf204f6e6f6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9dcb7896-c5bb-4f43-90f5-cbe23e8e0aa1"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
