# Generated by Django 4.1.5 on 2023-01-16 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0024_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0d01aed1-534f-455b-a530-2223a84be474"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9039df02-a046-4263-9c6a-5bdc5b415496"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
