# Generated by Django 4.1.5 on 2023-01-16 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0025_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("9ef72c5a-17ac-4e9a-90a3-1e401b35412b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("24d7fa82-dc94-4568-bee0-6951e1cf1bd5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
