# Generated by Django 4.1.5 on 2023-01-20 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_users", "0009_alter_estateuser_user_type"),
        ("estate_chats", "0026_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a5489b8e-b7a6-465b-880a-c150ccf65b49"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="online",
            field=models.ManyToManyField(blank=True, to="estate_users.estateuser"),
        ),
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_from_me",
                to="estate_users.estateuser",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a4c46eab-1eb9-4051-abcc-68a4d322f22f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_to_me",
                to="estate_users.estateuser",
            ),
        ),
    ]
