# Generated by Django 4.1.5 on 2023-01-20 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0027_alter_conversation_id_alter_conversation_online_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cdc12750-38be-4a9c-88de-43abf8064f34"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("93a67dd4-37f7-4c58-b4a8-fa6b7d782b63"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
