# Generated by Django 4.1.5 on 2023-01-20 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0028_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6f26635c-19bb-4112-81f9-412268f7330e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b155ece3-ec30-415e-aceb-5b39a508e557"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
