# Generated by Django 4.1.5 on 2023-01-20 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0029_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("862d40f4-f709-4060-90d2-ab644651ee41"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("206b5d2c-cbb6-429f-b641-04cbb0f063e8"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
