# Generated by Django 4.1.5 on 2023-01-23 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0030_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("131c5893-a92b-452f-a942-5c00772602ac"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("02516a70-5ec2-431b-ace4-22bd6ff41aeb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
