# Generated by Django 4.1.5 on 2023-01-24 00:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_chats", "0031_alter_conversation_id_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("df75b1f4-782d-48b6-9d37-dcd862914125"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c9c2436a-35af-45c4-ba9f-de8a3d119fcb"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
