# Generated by Django 4.1.5 on 2023-01-31 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("estate_users", "0012_alter_estateuser_user_category"),
        ("estate_chats", "0035_alter_message_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("1cd7a7f0-4b3f-45c1-9442-43767d74508a"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "online",
                    models.ManyToManyField(blank=True, to="estate_users.estateuser"),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("46d27d3d-afbc-4c36-87d0-44315cb35f24"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="GroupMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("ab3748c2-870a-4f71-a7a2-78b2e359686e"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.CharField(max_length=512)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estate_users.estateuser",
                    ),
                ),
                (
                    "group_conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_mesages",
                        to="estate_chats.groupconversation",
                    ),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
    ]
