# Generated by Django 4.1.5 on 2023-02-01 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0037_alter_groupconversation_id_alter_groupmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3bce69e8-c25a-4695-8c9b-62c17a05b7ec"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("961d5c60-b653-48e2-991f-f4122c1c9478"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("88192a9b-782e-4f25-985b-8cf7d10df884"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
