# Generated by Django 4.1.5 on 2023-02-01 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0038_alter_groupconversation_id_alter_groupmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cb34c7cf-955c-46ea-8f91-2e6b72be3fe3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7052e570-7e15-41a1-af04-74ab1e491b8b"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("0ecf6f4d-0847-40de-afdd-ea3c7c0f2b2e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
