# Generated by Django 4.1.5 on 2023-02-01 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0039_alter_groupconversation_id_alter_groupmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4b4bd5aa-4c8c-467b-b2fb-94c89da86c6f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("5279e90c-701f-44d0-b646-87e9b2a669f5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b3d49b65-e7af-48e5-8bd8-36f5cd4b444c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
