# Generated by Django 4.1.5 on 2023-02-01 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0040_alter_groupconversation_id_alter_groupmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2c19ce17-c3b1-474d-a6c2-8b8dde915afa"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("4849736c-73de-43e1-9e74-b68f0d577637"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d2d091b9-cade-41f8-8ee0-dc439159e3b3"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
