# Generated by Django 4.1.5 on 2023-02-02 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0041_alter_groupconversation_id_alter_groupmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupconversation",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("049be0c0-392e-45e9-93dd-2b840dec9ff5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="groupmessage",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d94619f9-0c3b-4d10-9991-7909adf19614"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e2c4e6e4-c1a5-4751-bfa2-33256cdcf925"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
