# Generated by Django 4.1.5 on 2023-02-04 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        (
            "estate_chats",
            "0042_alter_groupconversation_id_alter_groupmessage_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessage",
            name="from_user",
        ),
        migrations.RemoveField(
            model_name="groupmessage",
            name="group_conversation",
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.DeleteModel(
            name="GroupConversation",
        ),
        migrations.DeleteModel(
            name="GroupMessage",
        ),
    ]
